import React from 'react';

const TermsConditions = () => {
  return (
    <>
      <div className='flex flex-col space-y-8 w-full text-gray-600'>
        <h1 className='text-3xl'>Terms and Conditions</h1>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non tellus orci ac auctor augue mauris augue neque. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Viverra aliquet eget sit amet. Augue neque gravida in fermentum et sollicitudin ac. Suspendisse faucibus interdum posuere lorem ipsum dolor sit. Maecenas pharetra convallis posuere morbi leo. Id volutpat lacus laoreet non curabitur gravida arcu ac. Pellentesque adipiscing commodo elit at imperdiet dui. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel. Diam ut venenatis tellus in metus. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Vel facilisis volutpat est velit egestas dui id ornare arcu. Sed faucibus turpis in eu mi. In cursus turpis massa tincidunt dui ut. Praesent tristique magna sit amet purus gravida quis.</div>
        <div>Diam vulputate ut pharetra sit amet aliquam id. Augue mauris augue neque gravida in fermentum et sollicitudin. Diam donec adipiscing tristique risus. Gravida rutrum quisque non tellus orci ac auctor augue mauris. Aliquet nec ullamcorper sit amet. At quis risus sed vulputate odio ut enim blandit. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Facilisis gravida neque convallis a cras semper. Elit at imperdiet dui accumsan sit amet nulla facilisi morbi. Amet tellus cras adipiscing enim eu turpis egestas pretium aenean. Consectetur adipiscing elit duis tristique. Dictum varius duis at consectetur lorem donec massa sapien faucibus. Sed vulputate mi sit amet mauris commodo quis imperdiet.</div>
        <div>Sit amet mauris commodo quis. Enim sit amet venenatis urna cursus eget nunc scelerisque. Pellentesque habitant morbi tristique senectus et netus. Nullam eget felis eget nunc. Sagittis aliquam malesuada bibendum arcu vitae. Sagittis vitae et leo duis ut diam. Lectus sit amet est placerat in egestas erat imperdiet sed. Amet est placerat in egestas erat imperdiet sed euismod. Vestibulum sed arcu non odio euismod lacinia. Consectetur adipiscing elit duis tristique sollicitudin. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Ut diam quam nulla porttitor. Duis ultricies lacus sed turpis tincidunt id. Risus in hendrerit gravida rutrum.</div>
        <div>Quam quisque id diam vel. Enim lobortis scelerisque fermentum dui faucibus in ornare. Pellentesque massa placerat duis ultricies lacus sed turpis. Eu non diam phasellus vestibulum. Blandit massa enim nec dui. Quisque id diam vel quam elementum pulvinar. Viverra nam libero justo laoreet sit amet cursus. Proin libero nunc consequat interdum varius. Vestibulum lectus mauris ultrices eros in cursus turpis. Nunc sed blandit libero volutpat sed cras ornare arcu. Massa sed elementum tempus egestas sed sed risus pretium quam. Purus gravida quis blandit turpis cursus in. Varius duis at consectetur lorem donec. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget nullam.</div>
        <div>Sed euismod nisi porta lorem mollis aliquam ut. Nisi est sit amet facilisis. Massa sapien faucibus et molestie ac feugiat sed lectus vestibulum. Morbi tincidunt augue interdum velit euismod in pellentesque massa. Augue interdum velit euismod in pellentesque massa placerat duis. Adipiscing enim eu turpis egestas pretium aenean pharetra. Leo urna molestie at elementum eu. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Massa tincidunt dui ut ornare lectus sit. Urna nunc id cursus metus aliquam eleifend.</div>
        <div>Euismod quis viverra nibh cras pulvinar mattis nunc. Gravida rutrum quisque non tellus orci ac auctor. Accumsan lacus vel facilisis volutpat est velit. Arcu risus quis varius quam quisque. Ornare quam viverra orci sagittis eu volutpat odio facilisis. Cursus turpis massa tincidunt dui ut ornare lectus sit. Vel risus commodo viverra maecenas accumsan. Eu nisl nunc mi ipsum faucibus. Quis hendrerit dolor magna eget est lorem ipsum. Lorem mollis aliquam ut porttitor leo.</div>
        <div>Pulvinar sapien et ligula ullamcorper malesuada. Purus sit amet luctus venenatis lectus magna fringilla. Et netus et malesuada fames ac turpis egestas. Tellus orci ac auctor augue. Gravida rutrum quisque non tellus. Nulla malesuada pellentesque elit eget. Magnis dis parturient montes nascetur ridiculus mus. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Bibendum at varius vel pharetra vel turpis nunc eget. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Velit laoreet id donec ultrices tincidunt. Faucibus ornare suspendisse sed nisi. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sed nisi lacus sed viverra. Ipsum dolor sit amet consectetur adipiscing elit. Facilisi etiam dignissim diam quis enim.</div>
        <div>Nulla malesuada pellentesque elit eget. Vitae auctor eu augue ut lectus arcu bibendum. Non nisi est sit amet facilisis magna etiam tempor. Lacus luctus accumsan tortor posuere ac ut consequat semper. Sem nulla pharetra diam sit amet nisl. Aliquam eleifend mi in nulla posuere. Diam maecenas ultricies mi eget mauris pharetra. Cursus eget nunc scelerisque viverra mauris in. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. A scelerisque purus semper eget duis at tellus. Donec ac odio tempor orci dapibus ultrices.</div>
      </div>
    </>
  );
}

export default TermsConditions;
